/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package in.ignas.raselEntAdmin;

public final class R {
    public static final class attr {
    }
    public static final class id {
        public static final int activity_main_webview=0x7f060000;
    }
    public static final class layout {
        public static final int activity_main=0x7f020000;
    }
    public static final class raw {
        public static final int a=0x7f040000;
        public static final int conn=0x7f040001;
        public static final int sad=0x7f040002;
    }
    public static final class string {
        public static final int app_name=0x7f050000;
        public static final int title_activity_main=0x7f050001;
    }
    public static final class xml {
        public static final int network_security_config=0x7f030000;
    }
}
